[package]
name = "bone-rs"
version = "0.0.1"
edition = "2021"
description = "炳翰牛逼 !!!"
authors = ["wbytts@163.com"]
repository = "https://github.com/wbytts/bone-rs"
license = "MIT"

# 发布: cargo publish --registry crates-io
# 记得改版本号

[dependencies]
