[package]
name = "bone-rs"
version = "0.0.1"
edition = "2021"
description = "My First Rust Lib"
authors = ["wbytts@163.com"]
repository = "https://github.com/wbytts/bone-rs"
license = "MIT"

[dependencies]
